<?php

use Illuminate\Database\Seeder;
use App\Survey;
use Monolog\Handler\NullHandler;

class SurveySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                "user_id" => 1,
                "kode" => 'A.1',
                "nama_gedung" => 'Kelurahan Teritip',
                "longitude" => 117.002301,
                "latitude" => -1.169818,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => null,
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'A.2',
                "nama_gedung" => 'Kelurahan Manggar',
                "longitude" => 116.96307,
                "latitude" => -1.224963,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Kantor Kelurahan',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => 'Jln, Lumba-lumba',
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'A.3',
                "nama_gedung" => 'Kelurahan Lamaru',
                "longitude" => 116.977304,
                "latitude" => -1.207017,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => null,
                "fungsi_gedung" => null,
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'A.7',
                "nama_gedung" => 'Kelurahan Baru Ilir',
                "longitude" => 116.820902,
                "latitude" => -1.234366,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => null,
                "fungsi_gedung" => null,
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'A.8',
                "nama_gedung" => 'Kelurahan Baru Ulu',
                "longitude" => 116.816035,
                "latitude" => -1.224438,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => null,
                "fungsi_gedung" => null,
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'A.9',
                "nama_gedung" => 'Kelurahan Baru Tengah',
                "longitude" => 116.812818,
                "latitude" => -1.23136,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => null,
                "fungsi_gedung" => null,
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'A.11',
                "nama_gedung" => 'Kelurahan Sumber Rejo',
                "longitude" => 116.848582,
                "latitude" => -1.244618,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Gedung Kantor Kelurahan Sumber Rejo',
                "klasifikasi_gedung" => 'Bangunan Sederhana',
                "lokasi_gedung" => 'Jln.Sumber Rejo 1',
                "jumlah_lantai" => 2,
                "ketinggian" => 10,
                "luas_lantai" => 308.32,
                "luas_lantai_dasar" => 154.16,
                "luas_tanah" => 963.48,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'A.14',
                "nama_gedung" => 'Kelurahan Gunung Sari Ulu',
                "longitude" => 116.846668,
                "latitude" => -1.256916,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => null,
                "fungsi_gedung" => null,
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,

                "kode" => 'A.19',
                "nama_gedung" => 'Kelurahan Gunung Samarinda Baru',
                "longitude" => 116.860404,
                "latitude" => -1.234196,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Kantor Kelurahan',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => 'Jl.Indrakila',
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'A.21',
                "nama_gedung" => 'Kelurahan Graha Indah',
                "longitude" => 116.848048,
                "latitude" => -1.195136,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Kantor Kelurahan',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => 'Jln, Lumba-lumba',
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'B.4',
                "nama_gedung" => 'Kecamatan Balikpapan Utara',
                "longitude" => 116.861881,
                "latitude" => -1.20525,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Bangunan Milik Pemerintah kota Balikpapan',
                "fungsi_gedung" => 'Kantor Kelurahan',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => 'Perumahan Graha Indah',
                "jumlah_lantai" => 2,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => '2018',
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'C.1',
                "nama_gedung" => 'Sekretariat Daerah/Walikota Balikpapan',
                "longitude" => 116.827713,
                "latitude" => -1.276575,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Kantor',
                "klasifikasi_gedung" => 'Bangunan Tidak Sederhana',
                "lokasi_gedung" => 'Jalan Jend.Sudirman',
                "jumlah_lantai" => 2,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'C.8',
                "nama_gedung" => 'Dinas Pekerjaan Umum (DPU)',
                "longitude" => 116.892081,
                "latitude" => -1.242688,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Bangunan Gedung Kantor',
                "klasifikasi_gedung" => 'Tidak Sederhana ',
                "lokasi_gedung" => 'Jalan Ruhui Rahayu I no.1',
                "jumlah_lantai" => 2,
                "ketinggian" => 10,
                "luas_lantai" => 2004.8,
                "luas_lantai_dasar" => 1002.4,
                "luas_tanah" => 2,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'C.11',
                "nama_gedung" => 'Dinas Penanaman Modal dan Perizinan Terpadu (DPMPT)',
                "longitude" => 116.895174,
                "latitude" => -1.242956,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => null,
                "fungsi_gedung" => null,
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'C.12',
                "nama_gedung" => 'Dinas Perhubungan',
                "longitude" => 116.895174,
                "latitude" => -1.242956,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Kantor Dinas Perhubungan',
                "klasifikasi_gedung" => 'Bangunan tidak sederhana',
                "lokasi_gedung" => 'Jl.Ruhui Rahayu I No 5',
                "jumlah_lantai" => 5,
                "ketinggian" => 25,
                "luas_lantai" => 4373.45,
                "luas_lantai_dasar" => 874.69,
                "luas_tanah" => 4757.72,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'C.15',
                "nama_gedung" => 'Gabungan: Dinas Kependudukan dan Pencatatan Sipil;Dinas Pemberdayaan Perempuan, Perlindungan Anak dan Keluarga Berencana (DPPPKB)',
                "longitude" => 0,
                "latitude" => 0,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => null,
                "fungsi_gedung" => null,
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'C.16',
                "nama_gedung" => 'Gabungan: Dinas Ketenagakerjaan; Dinas Sosial; Badan Pengelola Pajak Daerah dan Retribusi;Badan Kepegawaian dan Pengembangan Sumber Daya Manusia',
                "longitude" => 0,
                "latitude" => 0,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => null,
                "fungsi_gedung" => null,
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'C.17',
                "nama_gedung" => 'Dinas Pemuda, Olahraga dan Pariwisata',
                "longitude" => 116.875545,
                "latitude" => -1.269722,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Kantor Dinas',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => 'Jln.Marsma iswahyudi',
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'C.21',
                "nama_gedung" => 'Dinas Komunikasi dan Informatika',
                "longitude" => 116.827619,
                "latitude" => -1.277617,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Kantor Pemerintah',
                "klasifikasi_gedung" => 'Bangunan Tidak Sederhana',
                "lokasi_gedung" => 'Jalan Jend Sudirman',
                "jumlah_lantai" => 1,
                "ketinggian" => 4,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => 'MUHAMMAD NOOR',
                "tahun_anggaran" => '2018',
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'D.3',
                "nama_gedung" => 'Squash Stadium',
                "longitude" => 116.890551,
                "latitude" => -1.244452,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Gedung Olahraga',
                "klasifikasi_gedung" => 'Khusus',
                "lokasi_gedung" => 'Jl. Syarifuddin Yoes No. 1 Gn. Bahagia Balikpapan Se"latitude"an, Kota Balikpapan',
                "jumlah_lantai" => 2,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => 'AM.Yusri Ramli',
                "tahun_anggaran" => '2012',
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'E.1',
                "nama_gedung" => 'Masjid Balikpapan Islamic Center (BIC)',
                "longitude" => 116.882044,
                "latitude" => -1.238045,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Tempat Ibadah',
                "klasifikasi_gedung" => 'Khusus',
                "lokasi_gedung" => 'Jl.Belibis',
                "jumlah_lantai" => 4,
                "ketinggian" => 0,
                "luas_lantai" => 25641.88,
                "luas_lantai_dasar" => 12820.94,
                "luas_tanah" => 139878.62,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => 'AM.Yusri Ramli',
                "tahun_anggaran" => '2012',
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'E.2',
                "nama_gedung" => 'Gedung Kesenian',
                "longitude" => 116.882044,
                "latitude" => -1.238045,
                "tanggal" => "2019-07-14",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Gedung Serbaguna',
                "klasifikasi_gedung" => 'Bangunan Tidak Sederhana',
                "lokasi_gedung" => 'Jl. Syarifuddin Yoes',
                "jumlah_lantai" => 1,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => 'AM.YUSRI RAMLI',
                "tahun_anggaran" => '2010',
                "cara_pelaksanaan" => 1,
                "youtube_id" => 'zcOsRSM7fr4',
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'F.1',
                "nama_gedung" => 'Pasar Pandansari',
                "longitude" => 116.824568,
                "latitude" => -1.238364,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Pasar',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => 'Jalan Pandan Sari',
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => 'MUHAIMIN, STMT',
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => 'zcOsRSM7fr4',
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'F.2',
                "nama_gedung" => 'Pasar Klandasan',
                "longitude" => 116.830868,
                "latitude" => -1.278043,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Pasar',
                "klasifikasi_gedung" => 'Khusus',
                "lokasi_gedung" => 'Jalan Jend.Sudirman',
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => 'MUHAIMIN, STMT',
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => 'zcOsRSM7fr4',
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'G.2 ',
                "nama_gedung" => 'Rumah Sakit Bersalin (RSB) Sayang Ibu',
                "longitude" => 116.821385,
                "latitude" => -1.234142,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Rumah Sakit Bersalin',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => 'JL.LETJEND SOEPRAPTO',
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'H.1 ',
                "nama_gedung" => 'SDN 001 Balikpapan Kota',
                "longitude" => 116.831037,
                "latitude" => -1.272312,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Sekolah',
                "klasifikasi_gedung" => 'Khusus',
                "lokasi_gedung" => 'Jln.Tanjung Pura',
                "jumlah_lantai" => 2,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'H.2 ',
                "nama_gedung" => 'SMPN 1 Balikpapan',
                "longitude" => 116.833661,
                "latitude" => -1.271073,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Sekolah',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'I.1',
                "nama_gedung" => 'Tennis Stadium',
                "longitude" => 116.885751,
                "latitude" => -1.251203,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'GEDUNG OLAHRAGA DAN WISMA ATLIT',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => 'JL.ASNAWI ARBAIN',
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'I.2',
                "nama_gedung" => 'Venue Dayung',
                "longitude" => 116.914624,
                "latitude" => -1.168215,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'GEDUNG OLAHRAGA DAN WISMA ATLIT',
                "klasifikasi_gedung" => null,
                "lokasi_gedung" => null,
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => null,
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'J.1',
                "nama_gedung" => 'Gedung Parkir',
                "longitude" => 116.832957,
                "latitude" => -1.276925,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Gedung Parkir, Aula dan Jajanan Kuliner',
                "klasifikasi_gedung" => 'Khusus',
                "lokasi_gedung" => 'Jl.Jendral Sudirman',
                "jumlah_lantai" => 7,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => 'Ahmad Safei, STMT',
                "tahun_anggaran" => '2015',
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'D.2',
                "nama_gedung" => 'Balikpapan Sport and Convention Center (BSCC)',
                "longitude" => 116.890178,
                "latitude" => -1.243648,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'GEDUNG OLAHRAGA DAN PERTEMUAN ',
                "klasifikasi_gedung" => 'Bangunan Khusus',
                "lokasi_gedung" => 'JL.RUHUI RAHAYU',
                "jumlah_lantai" => 3,
                "ketinggian" => 25,
                "luas_lantai" => 5180.08,
                "luas_lantai_dasar" => 2590.04,
                "luas_tanah" => 31779.88,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => 'AM.YUSRI RAMLI',
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
            [
                "user_id" => 1,
                "kode" => 'D.1',
                "nama_gedung" => 'Balikpapan Stadium',
                "longitude" => 116.94462,
                "latitude" => -1.23321,
                "tanggal" => "2019-07-18",
                "pemilik_gedung" => 'Pemerintah Kota Balikpapan',
                "fungsi_gedung" => 'Fasilitas Olah Raga /Lapangan Sepak Bola',
                "klasifikasi_gedung" => 'Bangunan Khusus',
                "lokasi_gedung" => 'Jalan Mulawarman',
                "jumlah_lantai" => 0,
                "ketinggian" => 0,
                "luas_lantai" => 0,
                "luas_lantai_dasar" => 0,
                "luas_tanah" => 0,
                "surat_bukti" => 1,
                "pptk" => null,
                "ppk" => 'AM.YUSRI RAMLI, STMT',
                "tahun_anggaran" => null,
                "cara_pelaksanaan" => 1,
                "youtube_id" => null,
                "foto" => null
            ],
        ];
        Survey::insert($data);
    }
}
